version: "3"

services:
  svelte-manga:
    container_name: svelte-manga
    build:
      context: .
      dockerfile: ./apps/svelte-manga/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - valiantlynx-turborepo

  breath-first-search:
    build:
      context: ./apps/breath-first-search
      dockerfile: Dockerfile  # Dockerfile is located within the context directory
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./apps/breath-first-search:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    networks:
      - valiantlynx-turborepo

  depth-first-search:
    build:
      context: ./apps/depth-first-search
      dockerfile: Dockerfile  # Dockerfile is located within the context directory
    ports:
      - 8001:8000
      - 5678:5678
    volumes:
      - ./apps/depth-first-search:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    networks:
      - valiantlynx-turborepo

  chatbot-ai:
    build:
      context: ./apps/chatbotAI
      dockerfile: Dockerfile  # Dockerfile is located within the context directory
    ports:
      - 8002:8000
      - 5678:5678
    volumes:
      - ./apps/chatbotAI:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    networks:
      - valiantlynx-turborepo

  langchain:
    build:
      context: ./apps/langchain
      dockerfile: Dockerfile  # Dockerfile is located within the context directory
    ports:
      - 8003:8000
      - 5678:5678
      - 8080:8080
    volumes:
      - ./apps/langchain:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload && /usr/local/bin/python /code/src/tutorial/combined-basics.py
    restart: always
    networks:
      - valiantlynx-turborepo

  logseq:
    image: ghcr.io/logseq/logseq-webapp:latest
    ports:
      - "8443:443"  # Use "8443:443" for HTTPS setup
    volumes:
      - ./apps/logseq/certs:/etc/nginx/certs  # SSL certificates for HTTPS setup
      - ./apps/logseq/ssl.conf:/etc/nginx/conf.d/ssl.conf  # Nginx configuration for HTTPS
    restart: always
    networks:
      - valiantlynx-turborepo
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  valiantlynx-turborepo:
    external: true
