version: '1.0'
services:
  svelte-manga-api-dev:
    build: .
    ports:
      - 8001:8001
    volumes:
      - .:/workspace:cached
    command: sh -c "uvicorn src.main:app --host=0.0.0.0 --port=8001 --reload"
    restart: always
    tty: true
    networks:
      - svelte-manga-api
    depends_on:
      - chroma
      
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
     # mouting the root folder that contains .git
    volumes:
      - ./assets/chroma:/chroma/.chroma/index # keep the chroma data persistent and easily accessible
    ports:
      - 8002:8000
    restart: always
    networks:
      - svelte-manga-api
    

networks:
  svelte-manga-api: # MIGHT NEED TO BE CHANGED. to be under the same network as all the other microservices
    driver: bridge