version: "3"

services:
  svelte-manga:
    container_name: svelte-manga
    build:
      context: .
      dockerfile: ./apps/svelte-manga/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - valiantlynx-turborepo

  next-web:
    container_name: next-web
    build:
      context: .
      dockerfile: ./apps/next-web/Dockerfile
    restart: always
    ports:
      - 3002:3000
    networks:
      - valiantlynx-turborepo
  express-api:
    container_name: express-api
    build:
      context: .
      dockerfile: ./apps/express-api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - valiantlynx-turborepo

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  valiantlynx-turborepo:
    external: true
