version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
      - "5173:5173"
      - "5174:5174"
      - "4173:4173"
    volumes:
      - .:/workspace
      - /workspace/node_modules
    restart: always
    profiles:
      - dev

  # Production monorepo service
  svelte-manga:
    container_name: svelte-manga
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-mono
    ports:
      - "3000:3000"
    restart: always
    profiles:
      - prod

  # Solo deployment service
  svelte-solo:
    container_name: svelte-solo
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-solo
    ports:
      - "3000:3000"
    restart: always
    profiles:
      - solo

