version: '1.0'
services:
  fastapi:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/workspace:cached
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
