version: "3"

services:
  svelte-manga:
    container_name: svelte-manga
    build:
      context: .
      dockerfile: ./apps/svelte-manga/Dockerfile
    restart: always
    ports:
      - 5173:5173
    networks:
      - valiantlynx-turborepo

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  valiantlynx-turborepo:
    external: true
