---
version: '3.8'

services:
  svelte-manga:
    image: valiantlynx/svelte-manga:latest
    container_name: svelte-manga
    restart: always
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - svelte-manga
    restart: unless-stopped
    networks:
      - monitoring

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - monitoring
    command: >
      certonly --webroot -w /var/www/certbot --force-renewal --email valiantlynxz@gmail.com
      -d astromanga.com -d www.astromanga.com
      -d auramanga.com -d www.auramanga.com
      -d comicbreeze.com -d www.comicbreeze.com
      -d comicharbor.com -d www.comicharbor.com
      -d ethermanga.com -d www.ethermanga.com
      -d ghostscans.com -d www.ghostscans.com
      -d knightscans.com -d www.knightscans.com
      -d mangaburst.com -d www.mangaburst.com
      -d mangacrest.com -d www.mangacrest.com
      -d mangafable.com -d www.mangafable.com
      -d mangaloom.com -d www.mangaloom.com
      -d mangaorbit.com -d www.mangaorbit.com
      -d mangaspectra.com -d www.mangaspectra.com
      -d mangawhiz.com -d www.mangawhiz.com
      -d mangazenith.com -d www.mangazenith.com
      -d nebulamanga.com -d www.nebulamanga.com
      -d otakureads.com -d www.otakureads.com
      -d owlscans.com -d www.owlscans.com
      -d pageturnmanga.com -d www.pageturnmanga.com
      -d pangeamanga.com -d www.pangeamanga.com
      -d pixelmanga.com -d www.pixelmanga.com
      -d quasarreads.com -d www.quasarreads.com
      -d readmangabliss.com -d www.readmangabliss.com
      -d redscans.com -d www.redscans.com
      -d scanshub.com -d www.scanshub.com
      -d starletmanga.com -d www.starletmanga.com
      -d stellarmanga.com -d www.stellarmanga.com
      -d waterscans.com -d www.waterscans.com
      -d whalescans.com -d www.whalescans.com
      --agree-tos --non-interactive

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    command: 
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - monitoring
  
networks:
  monitoring: {}
