version: '1.0'
services:
  whisper:
    build: .
    ports:
      - 8001:8000
      - 5679:5678
    volumes:
      - .:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always