version: '3.7'

services:
  kasm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:443"
    volumes:
      - ./kasm:/config
    environment:
      - ADMIN_PASS=amazonawS3a7abb
      - ALLOW_INSECURE_HTTP=true
    restart: always
    privileged: true
