version: '3.7'

services:
  kasm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./kasm:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ADMIN_PASS=amazonawS3a7abb
      - ALLOW_INSECURE_HTTP=true
    restart: always

  docker:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    depends_on:
      - kasm
